services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      NEO4J_URI: "bolt://neo4j:7687"
      NEO4J_USER: "neo4j"
      NEO4J_PASSWORD: "hyperstition"
    depends_on:
      neo4j:
        condition: service_healthy
    restart: unless-stopped

  neo4j:
    image: neo4j:5.17.0-community
    ports:
      - "7474:7474"
      - "7687:7687"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'RETURN 1;' | cypher-shell -u neo4j -p hyperstition"]
      interval: 15s
      timeout: 10s
      retries: 20
      start_period: 60s
    environment:
      NEO4J_AUTH: neo4j/hyperstition
      NEO4J_server_memory_heap_initial__size: "1G"
      NEO4J_server_memory_heap_max__size: "1G"
      NEO4J_server_jvm_additional: "-XX:+UseContainerSupport"
    volumes:
      - neo4j_data:/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  neo4j_data: