version: "3.8"  # Aunque es obsoleto, puede ayudar en versiones antiguas de Docker

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=hyperstition
    depends_on:
      neo4j:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  neo4j:
    image: neo4j:4.4.29-community
    environment:
      - NEO4J_AUTH=neo4j/hyperstition
      - NEO4J_dbms_connector_bolt_advertised__address=0.0.0.0:7687
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "hyperstition", "--format", "plain", "RETURN 1"]
      interval: 20s
      timeout: 15s
      retries: 10

volumes:
  neo4j_data:

